### ISSUE TITLE
Update the Navbar

### ISSUE THREAD

**Issue by Hackintosh-02** [codemaniac-sahil/javascript-clock#17]
Make changes in the Nav bar

- add effects on the nav bar.
- add proper spacing between contents.
- add hover to the nav elements.

**Comment by codemaniac-sahil** [comment]
Okay @Hackintosh-02 you can work on this issue.

**Comment by Yash-Var** [comment]
@codemaniac-sahil I have made a pr review  it and tell what other i can do on the navbar...
