### ISSUE TITLE
Update readme.md file

### ISSUE THREAD

**Issue by codemaniac-sahil** [codemaniac-sahil/javascript-clock#2]
Update readme.md file for this project.

**Comment by girijakar** [comment]
Assign this issue to me.

**Comment by codemaniac-sahil** [comment]
@girijakar you can work in this issue

**Comment by Tishachhabra** [comment]
Assign this issue to me

**Comment by codemaniac-sahil** [comment]
okay @Tishachhabra

**Comment by codemaniac-sahil** [comment]
@Tishachhabra are you working on this issue?
