### ISSUE TITLE
Alarm functionality

### ISSUE THREAD

**Issue by codemaniac-sahil** [codemaniac-sahil/javascript-clock#3]
Add alarm functionality to this project.

**Comment by AaryanSingh0017** [comment]
Assign this to me

**Comment by codemaniac-sahil** [comment]
@AaryanSingh0017 you can work on this issue

**Comment by AaryanSingh0017** [comment]
So i have to create a python code using tkinter library

**Comment by codemaniac-sahil** [comment]
But this project uses javascript

**Comment by AaryanSingh0017** [comment]
Okk create using html,css, javascript

**Comment by AaryanSingh0017** [comment]
In which file should i put the changes?

**Comment by codemaniac-sahil** [comment]
on script.js

**Comment by JawHawk** [comment]
@codemaniac-sahil I can work on this issue, kindly can I get assigned too ?

**Comment by codemaniac-sahil** [comment]
yes @JawHawk

**Comment by JawHawk** [comment]
Solved this issue under PR #12
