### ISSUE TITLE
Structure the files

### ISSUE THREAD

**Issue by codemaniac-sahil** [codemaniac-sahil/javascript-clock#5]
Structure all the files of this project.

**Comment by Misterr-H** [comment]
@codemaniac-sahil i would like to work upon it

**Comment by codemaniac-sahil** [comment]
@Misterr-H you can work on this issue.

**Comment by Misterr-H** [comment]
@codemaniac-sahil thankyou

**Comment by Misterr-H** [comment]
@codemaniac-sahil Please review 
thanks again
